fb.login = your_login_here
fb.pass = your_password_here
fb.group.ids = 1489819158035015
posts.to.fetch = 10

# Multiple groups example:
# fb.group.ids = 1489819158035015,9876543210

#possible parameters
export.to = postgres & excel
